### ISSUE TITLE
Generate AWS headers using aws-sigv4 plugin

### ISSUE THREAD

**Issue by nishit-shah** [Nordstrom/artillery-plugin-aws-sigv4#7]
I have setup my aws account and have creds and region configured at ~/.aws/ path
my account is having region:us-east-1
Also configured the json file as displayed below for aws-sigv4 plugin:

```
{
	"config": {
		"plugins": {
			"aws-sigv4": {
				"serviceName": "execute-api"
			}
		},
		"target": "https://hosttest.amazonaws.com",
		"phases": [{
			"duration": 60,
			"arrivalRate": 20
		}],
		"defaults": {
			"headers": {
			}
		}
	},
	"scenarios": [{
		"beforeRequest": "addAmazonSignatureV4",
		"flow": [{
			"get": {
				"url": "/testapi"
			}
		}]
	}]
}
```

When sent the request with following command:
artillery run test.json
Got error saying:
Type error: Not a string or buffer

Note:Also updated node from 4.4.5 to 7.x stable version but still getting the same error.

[@erikerikson edit 09/12/2016@12pPST: improve JSON formatting]

**Comment by erikerikson** [comment]
reproduction stack trace:
```
-TypeError: Data must be a string or a buffer
at Hmac.update (crypto.js:74:16)
at Object.hmac (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/node_modules/aws-sdk/lib/util.js:384:50)
at V4.signature (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/node_modules/aws-sdk/lib/signers/v4.js:132:37)
at V4.authorization (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/node_modules/aws-sdk/lib/signers/v4.js:104:36)
at V4.addAuthorization (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/node_modules/aws-sdk/lib/signers/v4.js:46:12)
at Object.addAmazonSignatureV4 (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/lib/aws-sigv4.js:58:20)
at AwsSigV4Plugin.scriptConfig.processor.addAmazonSignatureV4 (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery-plugin-aws-sigv4/lib/aws-sigv4.js:77:26)
at iteratee (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery/node_modules/artillery-core/lib/engine_http.js:200:9)
at ~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery/node_modules/async/lib/async.js:181:20
at iterate (~/.nvm/versions/node/v7.2.0/lib/node_modules/artillery/node_modules/async/lib/async.js:262:13)
```

For the record, we have generally worked and tested using 4.x, so updating node should be unnecessary.

**Comment by erikerikson** [comment]
@nishit-shah please define a valid region for the aws-sdk.  For example, export/set AWS_REGION in your console.  Another option is setting a default region in your ~/.aws/config file.  Do be sure it is the region in which your target is defined.

The error occurs when the request has no region and cannot inherit one from the SDK, thus the reference to it in creating the credential string fails [here](https://github.com/aws/aws-sdk-js/blob/master/lib/signers/v4.js#L207).

**Comment by erikerikson** [comment]
Actually, reading the code to avoid this for future users, this plugin should work in a node v0.10 environment as well.

**Comment by nishit-shah** [comment]
Hey Erik,

i already have region set in my config file. see this
location: ~/.aws/config
[default]
output = json
region = us-east-1

still i was getting this error. Not sure, why this is not working.

**Comment by erikerikson** [comment]
Hmm.  Perhaps check that your credentials are set up properly in your `~/.aws/credentials` file?

If so... I don't have a reproduction here.  Could you help me determine what is leading to this?  Perhaps you could hack your `aws-sdk` to report what empty, null, or undefined values it is attempting to use?

**Comment by erikerikson** [comment]
Happy to help but without a reproduction, it's hard to do so.  Thanks!

**Comment by nishit-shah** [comment]
all things are in place creds,region...can you check if you have region as us-east-1 instead of us-west-2, does it load the config and executes the request?

**Comment by nishit-shah** [comment]
if i pass region "us-east-1" instead of aws.config.region in the js file then it works well. so not sure why aws.config.region is not able to read the region.

Hope this will be helpful.

**Comment by erikerikson** [comment]
It definitely could be @nishit-shah.
By:
> if i pass region "us-east-1" instead of aws.config.region in the js file

do you mean here:
https://github.com/Nordstrom/artillery-plugin-aws-sigv4/blob/master/lib/aws-sigv4.js#L72
?

If so, it appears that your aws-sdk isn't picking up your region setting properly, either because of a bug in that library, you have AWS_CONFIG_FILE defined and set to a different location, or a misconfiguration of your config file.  I suppose another option could be that you have AWS_PROFILE set, expecting it to apply only to the credentials file but it is also applying to your config file.  It's hard to say.

To bypass (but not solve) the region load failure, you could set AWS_DEFAULT_REGION:
Win:
`set AWS_DEFAULT_REGION=us-east-1`
OSx/Linux:
`export AWS_DEFAULT_REGION=us-east-1`

We assume, in this plugin, full pre-configuration of the SDK so I think that I'm going to leave this issue closed for now.  The associated PR should detect that value not being set and warn accordingly.

This written, I'm happy to continue discussing this if there's a way that I can be of help.

**Comment by nishit-shah** [comment]
Yes, i set explicit value of region on that line and ran the test and it gave proper results.

Regarding setting up SDK, i have tried all the given ways but still stuck and that's frustrating!!!!

Anyways thanks for all the efforts and will update here if anything and please let me know if you come across anything that can be helpful.

Thanks,
Nishit.

**Comment by erikerikson** [comment]
Sorry I don't have the capacity to do better.

You may create some luck by openning an issue asking the aws-sdk developers over at https://github.com/aws/aws-sdk-js/ why your region config isn't being loaded.
